### ISSUE TITLE
Crash on explosion on claimed land

### ISSUE THREAD

**Issue by CapdinCrando** [CapdinCrando/Guilds#15]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 5/11/19 4:29 PM
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at parallaxscience.guilds.events.ChunkEvents.onDetonate(ChunkEvents.java:122)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_20_ChunkEvents_onDetonate_Detonate.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:591)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:134)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1169)
	at net.minecraft.world.World.func_72876_a(World.java:2300)
	at net.minecraft.entity.item.EntityTNTPrimed.func_70515_d(SourceFile:99)
	at net.minecraft.entity.item.EntityTNTPrimed.func_70071_h_(SourceFile:89)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at parallaxscience.guilds.events.ChunkEvents.onDetonate(ChunkEvents.java:122)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_20_ChunkEvents_onDetonate_Detonate.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:591)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:134)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1169)
	at net.minecraft.world.World.func_72876_a(World.java:2300)
	at net.minecraft.entity.item.EntityTNTPrimed.func_70515_d(SourceFile:99)
	at net.minecraft.entity.item.EntityTNTPrimed.func_70071_h_(SourceFile:89)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: minecraft:tnt (net.minecraft.entity.item.EntityTNTPrimed)
	Entity ID: 5144
	Entity Name: Block of TNT
	Entity's Exact location: 0.51, 69.00, 134.30
	Entity's Block location: World: (0,69,134), Chunk: (at 0,4,6 in 0,8; contains blocks 0,0,128 to 15,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.00, -0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['KuatYards'/1588, l='world', x=-1.71, y=78.81, z=148.99], EntityPlayerMP['CapdinCrando'/2228, l='world', x=2.53, y=69.00, z=132.42]]
	Chunk stats: ServerChunkCache: 305 Drop: 0
	Level seed: 6653850018465125600
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-16,64,124), Chunk: (at 0,4,12 in -1,7; contains blocks -16,0,112 to -1,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6172 game time, 6172 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 132960 (now: false), thunder time: 36910 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.0-8-amd64
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 188800944 bytes (180 MB) / 1008730112 bytes (962 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 1 total; -Xmx4G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source         | Signature                                |
	|:------ |:--------- |:------------ |:-------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar  | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar  | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | server.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2836 | server.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | guilds    | ALPHA 1.0    | guilds-0.1.jar | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 2 / 20; [EntityPlayerMP['KuatYards'/1588, l='world', x=-1.71, y=78.81, z=148.99], EntityPlayerMP['CapdinCrando'/2228, l='world', x=2.53, y=69.00, z=132.42]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by CapdinCrando** [comment]
Fixed with dfd99d7f0531fbfa030e24f777d5d65eb1f5628e

**Comment by CapdinCrando** [comment]
Further fixed by 347db5f04b5bf45b0e24a6090732cf000a797f63 and 3d3d7f99d8e2f2a82250edc731d245ea3e607860
